function output_path = export_png(fig, output_directory, output_name)
%EXPORT_PNG Apply the shared thesis style and export a 1600-by-960 PNG.

arguments
    fig (1,1) matlab.ui.Figure
    output_directory (1,1) string
    output_name (1,1) string
end

if ~isfolder(output_directory)
    mkdir(output_directory);
end

figure_cleanup = onCleanup(@() delete_if_valid(fig));

axes_handles = findall(fig, 'Type', 'axes');
for idx = 1:numel(axes_handles)
    ax = axes_handles(idx);
    set(ax, ...
        'Box', 'on', ...
        'Color', 'white', ...
        'FontSize', 11, ...
        'LineWidth', 0.8, ...
        'TickLabelInterpreter', 'latex', ...
        'XGrid', 'on', ...
        'YGrid', 'on', ...
        'ZGrid', 'on', ...
        'GridAlpha', 0.18, ...
        'MinorGridAlpha', 0.10);

    labels = [ax.XLabel, ax.YLabel, ax.ZLabel];
    set(labels, 'Interpreter', 'latex', 'FontSize', 13);
    set(ax.Title, ...
        'Interpreter', 'latex', ...
        'FontSize', 13, ...
        'FontWeight', 'normal');
end

legend_handles = findall(fig, 'Type', 'legend');
set(legend_handles, ...
    'Interpreter', 'latex', ...
    'FontSize', 10, ...
    'Box', 'off');

colorbar_handles = findall(fig, 'Type', 'colorbar');
for idx = 1:numel(colorbar_handles)
    cb = colorbar_handles(idx);
    set(cb, ...
        'FontSize', 11, ...
        'LineWidth', 0.8, ...
        'TickLabelInterpreter', 'latex');
    set(cb.Label, 'Interpreter', 'latex', 'FontSize', 13);
end

drawnow;
output_path = fullfile(output_directory, output_name + ".png");
set(fig, ...
    'PaperPositionMode', 'manual', ...
    'PaperUnits', 'inches', ...
    'PaperPosition', [0, 0, 8, 4.8], ...
    'PaperSize', [8, 4.8]);
print(fig, output_path, '-dpng', '-r200');
delete(fig);
end

function delete_if_valid(fig)
if isvalid(fig)
    delete(fig);
end
end
