function output_path = binary_detection(output_directory)
%BINARY_DETECTION Plot equal-prior Gaussian decision regions.

arguments
    output_directory (1,1) string
end

mean_h0 = 40;
mean_h1 = 60;
standard_deviation = 10;
observation_threshold = (mean_h0+mean_h1)/2;
likelihood_ratio_threshold = 1;
num_points = 501;
observation = linspace(mean_h0-4*standard_deviation, ...
    mean_h1+4*standard_deviation,num_points);
threshold_index = find(observation == observation_threshold,1);

density_h0 = exp(-0.5*((observation-mean_h0)/standard_deviation).^2) / ...
    (standard_deviation*sqrt(2*pi));
density_h1 = exp(-0.5*((observation-mean_h1)/standard_deviation).^2) / ...
    (standard_deviation*sqrt(2*pi));
false_alarm_probability = 0.5*erfc((observation_threshold-mean_h0)/ ...
    (standard_deviation*sqrt(2)));
detection_probability = 0.5*erfc((observation_threshold-mean_h1)/ ...
    (standard_deviation*sqrt(2)));
assert(abs(false_alarm_probability-0.158655253931457) < 1e-12);
assert(abs(detection_probability-0.841344746068543) < 1e-12);

[fig, colors] = thesis.plot.new_figure();
ax = axes(fig);
hold(ax,'on');
left = 1:threshold_index;
right = threshold_index:num_points;
correct_rejection = fill(ax,[observation(left),fliplr(observation(left))], ...
    [density_h0(left),zeros(size(left))],colors.sky, ...
    'FaceAlpha',0.28,'EdgeColor','none');
false_alarm = fill(ax,[observation(right),fliplr(observation(right))], ...
    [density_h0(right),zeros(size(right))],colors.red, ...
    'FaceAlpha',0.28,'EdgeColor','none');
miss = fill(ax,[observation(left),fliplr(observation(left))], ...
    [density_h1(left),zeros(size(left))],colors.purple, ...
    'FaceAlpha',0.24,'EdgeColor','none');
detection = fill(ax,[observation(right),fliplr(observation(right))], ...
    [density_h1(right),zeros(size(right))],colors.green, ...
    'FaceAlpha',0.24,'EdgeColor','none');
density_h0_line = plot(ax,observation,density_h0, ...
    'Color',colors.blue,'LineWidth',2.0);
density_h1_line = plot(ax,observation,density_h1, ...
    'Color',colors.orange,'LineWidth',2.0);
threshold_line = xline(ax,observation_threshold,'--','$y_{\mathrm{th}}$', ...
    'Color',colors.gray,'LineWidth',1.6, ...
    'LabelVerticalAlignment','middle', ...
    'LabelHorizontalAlignment','left','Interpreter','latex');

xlabel(ax,'Observation, $y$');
ylabel(ax,'Conditional density, $p_{Y\mid H_i}(y)$');
title(ax,'Binary hypothesis decision regions');
xlim(ax,[observation(1),observation(end)]);
ylim(ax,[0,1.08*max([density_h0,density_h1])]);
legend(ax,[correct_rejection,false_alarm,miss,detection, ...
    density_h0_line,density_h1_line,threshold_line], ...
    {'$P_{CR}$','$P_{FA}$','$P_M$','$P_D$', ...
    '$p_{Y\mid H_0}$','$p_{Y\mid H_1}$','$y_{\mathrm{th}}$'}, ...
    'Location','northoutside','NumColumns',4);

fprintf(['Observation threshold y_th = %.1f (grid sample %d) ' ...
    'corresponds to gamma_LR = %.1f; P_FA = %.6f; P_D = %.6f\n'], ...
    observation_threshold,threshold_index,likelihood_ratio_threshold, ...
    false_alarm_probability,detection_probability);
output_path = thesis.plot.export_png(fig,output_directory, ...
    'error_probabilities');
end
