function output_path = scf_detection(output_directory,stream)
%SCF_DETECTION Demonstrate thresholded BPSK SCF detection.

arguments
    output_directory (1,1) string
    stream (1,1) RandStream
end

num_symbols = 16384;
modulation_order = 2;
symbol_rate_hz = 100e3;
sample_rate_hz = 1e6;
center_frequency_hz = 50e3;
rolloff = 1.0;
ebn0_db = 14;
samples_per_symbol = sample_rate_hz/symbol_rate_hz;

clean_signal = thesis.signal.qam_srrc_waveform(num_symbols, ...
    sample_rate_hz,symbol_rate_hz,center_frequency_hz, ...
    modulation_order,rolloff,stream,'UnitAveragePower',true);
clean_signal = clean_signal/sqrt(mean(abs(clean_signal).^2));
sample_snr_db = ebn0_db + 10*log10(log2(modulation_order)) - ...
    10*log10(samples_per_symbol);
[received_signal,noise] = thesis.signal.add_complex_awgn( ...
    clean_signal,sample_snr_db,stream);

cycle_frequencies_hz = (0:symbol_rate_hz:sample_rate_hz/2).';
max_lag = 50;
num_frequencies = 200;
frequency_hz = (-num_frequencies/2:num_frequencies/2-1) * ...
    (sample_rate_hz/num_frequencies);
cyclic_autocorrelation = thesis.signal.symmetric_caf(received_signal, ...
    cycle_frequencies_hz,sample_rate_hz,max_lag);
spectral_correlation = fftshift(fft(cyclic_autocorrelation, ...
    num_frequencies,2),2);

test_statistic = abs(spectral_correlation).^2;
threshold_scale = 1e-2;
estimated_power = mean(abs(received_signal).^2);
detection_threshold = threshold_scale*estimated_power^2;

slice_peaks = max(test_statistic,[],2);
detected_rows = find((cycle_frequencies_hz > 0) & ...
    (slice_peaks > detection_threshold));
[~,peak_columns] = max(test_statistic(detected_rows,:),[],2);
detected_cycle_frequencies_hz = cycle_frequencies_hz(detected_rows);
detected_frequencies_hz = frequency_hz(peak_columns);
detected_peaks = slice_peaks(detected_rows);

[fig, colors] = thesis.plot.new_figure();
ax = axes(fig);
hold(ax,'on');
display_rows = cycle_frequencies_hz > 0;
mesh_handle = mesh(ax,frequency_hz/1e3, ...
    cycle_frequencies_hz(display_rows)/1e3, ...
    test_statistic(display_rows,:), ...
    'FaceColor','none','EdgeColor',colors.blue, ...
    'EdgeAlpha',0.70,'LineWidth',0.7);
threshold_handle = surf(ax,frequency_hz/1e3, ...
    cycle_frequencies_hz(display_rows)/1e3, ...
    detection_threshold*ones(nnz(display_rows),num_frequencies), ...
    'FaceColor',colors.orange,'FaceAlpha',0.30, ...
    'EdgeColor',colors.orange,'EdgeAlpha',0.15);
peak_handle = scatter3(ax,detected_frequencies_hz/1e3, ...
    detected_cycle_frequencies_hz/1e3,detected_peaks,55, ...
    colors.green,'filled','MarkerEdgeColor','white','LineWidth',0.8);

view(ax,225,20);
xlabel(ax,'Spectral frequency, $f$ (kHz)');
ylabel(ax,'Cycle frequency, $\alpha$ (kHz)');
zlabel(ax,'$T_y^{\alpha}(f)=|\widehat{S}_y^{\alpha}(f)|^2$');
title(ax,'Received BPSK SCF-Based Detection');
xlim(ax,[-sample_rate_hz,sample_rate_hz]/(2e3));
ylim(ax,[symbol_rate_hz,sample_rate_hz/2]/1e3);
set(ax,'ZScale','log');
zlim(ax,[detection_threshold/10, ...
    1.2*max(test_statistic(display_rows,:),[],'all')]);
legend(ax,[mesh_handle,threshold_handle,peak_handle], ...
    {'$T_y^{\alpha}(f)$', ...
    '$\gamma_{\mathrm{CFD}}=\beta\widehat{P}_y^2$', ...
    'Detected $(\widehat{R}_s,\widehat{f}_c)$'}, ...
    'Location','northeast');

measured_sample_snr_db = 10*log10(mean(abs(clean_signal).^2) / ...
    mean(abs(noise).^2));
assert(abs(measured_sample_snr_db-sample_snr_db) < 1e-10, ...
    'thesis:scf_detection:IncorrectNoisePower', ...
    'The realized sample SNR differs from its request.');
fprintf('Requested sample SNR = %.3f dB; measured = %.3f dB\n', ...
    sample_snr_db,measured_sample_snr_db);
fprintf('beta = %.3g; gamma_CFD = %.6g\n', ...
    threshold_scale,detection_threshold);
for detection_index = 1:numel(detected_rows)
    fprintf(['Detected alpha = %.1f kHz at f = %.1f kHz ' ...
        '(peak/gamma_CFD = %.2f)\n'], ...
        detected_cycle_frequencies_hz(detection_index)/1e3, ...
        detected_frequencies_hz(detection_index)/1e3, ...
        slice_peaks(detected_rows(detection_index))/detection_threshold);
end
non_target_rows = cycle_frequencies_hz > 0 & ...
    cycle_frequencies_hz ~= symbol_rate_hz;
fprintf('Largest non-target peak/gamma_CFD = %.3f\n', ...
    max(slice_peaks(non_target_rows))/detection_threshold);

assert(any(detected_cycle_frequencies_hz == symbol_rate_hz), ...
    'thesis:scf_detection:MissedSymbolRate', ...
    'The known symbol-rate slice was not detected.');
assert(isscalar(detected_cycle_frequencies_hz), ...
    'thesis:scf_detection:FalseCycleFrequencyDetection', ...
    'At least one non-symbol-rate slice exceeded the threshold.');
known_row = find(cycle_frequencies_hz == symbol_rate_hz,1);
[~,known_peak_column] = max(test_statistic(known_row,:));
assert(abs(frequency_hz(known_peak_column)-center_frequency_hz) <= ...
    sample_rate_hz/num_frequencies, ...
    'thesis:scf_detection:IncorrectCenterFrequency', ...
    'The detected carrier is farther than one DFT bin from its target.');

output_path = thesis.plot.export_png(fig,output_directory,'threshold_3d');
end
