function generate_all_plots()
%GENERATE_ALL_PLOTS Rebuild every MATLAB-generated thesis figure.

matlab_directory = fileparts(mfilename('fullpath'));
original_directory = pwd;
restore_directory = onCleanup(@() cd(original_directory));
cd(matlab_directory);
addpath(matlab_directory);

scripts = { ...
    'gaussian_pdf.m', ...
    'random_signal_params.m', ...
    'qam_rect.m', ...
    'energy_spectral_density.m', ...
    'qam_srrc.m', ...
    'spectrum_sensing.m', ...
    'detection_2d.m', ...
    'detection_3d.m', ...
    'koch_sca.m'};

for idx = 1:numel(scripts)
    script_path = fullfile(matlab_directory, scripts{idx});
    escaped_path = strrep(script_path, '''', '''''');
    fprintf('Generating plots with %s ...\n', scripts{idx});
    evalin('base', sprintf('run(''%s'');', escaped_path));
end

plot_names = { ...
    'gaussian_pdf.png', 'X_mean_std.png', '2qam_time.png', ...
    'autocorrelogram.png', 'periodogram.png', 'psd.png', ...
    'cyclic_autocorrelogram.png', 'scf.png', 'esd.png', ...
    'qam_srrc.png', 'spectrum_sensing.png', ...
    'error_probabilities.png', 'threshold_3d.png', 'qam_srrc_rs.png'};
plots_directory = fullfile(matlab_directory, '..', 'plots');
for idx = 1:numel(plot_names)
    metadata = imfinfo(fullfile(plots_directory,plot_names{idx}));
    assert(metadata.Width == 1600 && metadata.Height == 960, ...
        'Plot %s is %d-by-%d instead of 1600-by-960.', ...
        plot_names{idx},metadata.Width,metadata.Height);
end

close all force;
fprintf('Generated all thesis plots in %s.\n', ...
    plots_directory);
end
