function output_path = thesis_export(fig, output_name)
%THESIS_EXPORT Apply shared styling and export a thesis plot as a PNG.

axes_handles = findall(fig, 'Type', 'axes');
for idx = 1:numel(axes_handles)
    ax = axes_handles(idx);
    set(ax, ...
        'Box', 'on', ...
        'Color', 'white', ...
        'FontSize', 11, ...
        'LineWidth', 0.8, ...
        'TickLabelInterpreter', 'latex', ...
        'XGrid', 'on', ...
        'YGrid', 'on', ...
        'ZGrid', 'on', ...
        'GridAlpha', 0.18, ...
        'MinorGridAlpha', 0.10);

    labels = [ax.XLabel, ax.YLabel, ax.ZLabel];
    set(labels, 'Interpreter', 'latex', 'FontSize', 13);
    set(ax.Title, ...
        'Interpreter', 'latex', ...
        'FontSize', 13, ...
        'FontWeight', 'normal');
end

legend_handles = findall(fig, 'Type', 'legend');
set(legend_handles, ...
    'Interpreter', 'latex', ...
    'FontSize', 10, ...
    'Box', 'off');

colorbar_handles = findall(fig, 'Type', 'colorbar');
for idx = 1:numel(colorbar_handles)
    cb = colorbar_handles(idx);
    set(cb, ...
        'FontSize', 11, ...
        'LineWidth', 0.8, ...
        'TickLabelInterpreter', 'latex');
    set(cb.Label, 'Interpreter', 'latex', 'FontSize', 13);
end

drawnow;
matlab_directory = fileparts(mfilename('fullpath'));
plots_directory = fullfile(matlab_directory, '..', 'plots');
output_path = fullfile(plots_directory, [output_name, '.png']);
set(fig, ...
    'PaperPositionMode', 'manual', ...
    'PaperUnits', 'inches', ...
    'PaperPosition', [0, 0, 8, 4.8], ...
    'PaperSize', [8, 4.8]);
print(fig, output_path, '-dpng', '-r200');
close(fig);
end
