-----------------------------------------------------------------------------------------------------
--! @Author:         Anthony A. Stock, intern (NASA GRC/LCI)
--! @Creation-Date:  9 October 2020
--! @Module-Name:    Generic Complex Multiply testbench
--! @Project-Name:   Space Telecommunications Radio System
--! @Target-Device:  xc7z045fbg676-1
--! @Vivado-Version: 2019.2.1
--! @Git-Tag:        xxxx
--!
--! Revision 0.01 - Anthony A. Stock -- file created
------------------------------------------------------------------------------------------------------

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;
use std.textio.all;

--! @Module-Description
--! This testbench uses input files generated by a script, generate_inputs.py,
--! which also produces a file of theoretical outputs to be compared against
--! the output of this testbench.

entity GenericComplexMultiply_tb is
--  Port ( );
end GenericComplexMultiply_tb;

architecture Behavioral of GenericComplexMultiply_tb is

component GenericComplexMultiply
  generic (
    LengthA     : integer range 2 to 32 := 16; --! Number of bits in operand A.
    LengthB     : integer range 2 to 32 := 16; --! Number of bits in operand B.
    Latency     : integer range 2 to 6  := 2;  --! Total cycles of latency to do an operation.
    BitstoTrunc : integer               := 0;  --! Allows the ability to trim most significant bits (without saturation!).
    BitstoRound : integer               := 0   --! Allows the ability to trim least significant bits through symmetric rounding.
  );
  port (
    -- Module inputs
    Clock           : in  std_logic;                          --! Global clock
    Reset           : in  std_logic;                          --! Synchronous reset
    RealA_in        : in  signed(LengthA-1 downto 0);         --! Signed input 1
    ImagA_in        : in  signed(LengthA-1 downto 0);         --! Signed input 2
    RealB_in        : in  signed(LengthB-1 downto 0);         --! Signed input 3
    ImagB_in        : in  signed(LengthB-1 downto 0);         --! Signed input 4
    SampleInValid  :  in std_logic;                           --! is input valid
    SampleInLast   :  in std_logic;                           --! marker to delineate two back-to-back sequences of inputs
    SampleOutReady :  in std_logic;                           --! is following module ready to accept input
    -- Module outputs
    ProductReal       : out signed(LengthA+LengthB-BitstoTrunc-BitstoRound downto 0);  --! ProductReal      = A_in * C_in - B_in * D_in
    ProductImaginary  : out signed(LengthA+LengthB-BitstoTrunc-BitstoRound downto 0);  --! ProductImaginary = A_in * D_in + B_in * C_in
    SampleOutValid : out std_logic;                                -- is output valid
    SampleOutLast  : out std_logic;                                -- marker to delineate two back-to-back sequences of inputs
    SampleInReady  : out std_logic                                 -- tell preceding module that we're ready for input
  );
end component;

------------------------------------------------------------------------------------------------------
-- Constants
------------------------------------------------------------------------------------------------------
constant LengthA     : integer := 4; --! Number of bits in operand A.
constant LengthB     : integer := 4; --! Number of bits in operand B.
constant Latency     : integer := 2; --! Total cycles of latency to do an operation.
constant BitstoTrunc : integer := 0; --! Allows the ability to trim most significant bits (without saturation!).
constant BitstoRound : integer := 0; --! Allows the ability to trim least significant bits through symmetric rounding.

constant ClockPeriod    : time := 10 ns;
constant read_filename  : string := "../../../../../test/inputs.csv";
constant write_filename : string := "../../../../../test/output.txt";
file write_file         : text;

------------------------------------------------------------------------------------------------------
-- Input Signals
------------------------------------------------------------------------------------------------------
signal Clock             :  std_logic := '0';               --! Global clock
signal Reset             :  std_logic := '1';               --! Synchronous reset
signal RealA_in          :  signed(LengthA-1 downto 0); --! Signed input 1
signal ImagA_in          :  signed(LengthA-1 downto 0); --! Signed input 2
signal RealB_in          :  signed(LengthB-1 downto 0); --! Signed input 3
signal ImagB_in          :  signed(LengthB-1 downto 0); --! Signed input 4
signal SampleInValid     :  std_logic := '0';
signal SampleInLast      :  std_logic := '0';
signal SampleOutReady    :  std_logic := '0';

------------------------------------------------------------------------------------------------------
-- Output Signals
------------------------------------------------------------------------------------------------------
signal ProductReal       :  signed(LengthA+LengthB-BitstoTrunc-BitstoRound downto 0);  --! ProductReal      = A_in * C_in - B_in * D_in
signal ProductImaginary  :  signed(LengthA+LengthB-BitstoTrunc-BitstoRound downto 0);  --! ProductImaginary = A_in * D_in + B_in * C_in
signal SampleOutValid    :  std_logic;
signal SampleOutLast     :  std_logic;
signal SampleInReady     :  std_logic;

begin
  uut: GenericComplexMultiply
    generic map(
    LengthA => LengthA,
    LengthB => LengthB,
    Latency     => Latency,
    BitstoTrunc => BitstoTrunc,
    BitstoRound => BitstoRound
    )
    port map(
    Clock            => Clock,
    Reset            => Reset,
    RealA_in         => RealA_in,
    ImagA_in         => ImagA_in,
    RealB_in         => RealB_in,
    ImagB_in         => ImagB_in,
    SampleInValid    => SampleInValid,
    SampleInLast     => SampleInLast,
    SampleOutReady   => SampleOutReady,
    ProductReal      => ProductReal,
    ProductImaginary => ProductImaginary,
    SampleOutValid   => SampleOutValid,
    SampleOutLast    => SampleOutLast,
    SampleInReady    => SampleInReady
  );

--
-- Generate Clock
--
Clock_proc : process
begin
  wait for ClockPeriod / 2;
  Clock <= not Clock;
end process Clock_proc;

--
-- Calculate Latency
--
CheckLatency_proc : process
  variable InputStart      : time;
  variable OutputStart     : time;
  variable MeasuredLatency : integer;
begin
  -- use control signals to find difference b/w when input starts and module begins producing output
  wait until rising_edge(SampleInValid);
  InputStart := now;
  wait until rising_edge(SampleOutValid);
  OutputStart := now;

  MeasuredLatency := (OutputStart - InputStart) / ClockPeriod;
  if Latency = measuredLatency then
    report "TEST PASS: Latency matches expected latency of " & integer'image(Latency);
  else
    report "TEST FAIL: Latency of " & integer'image(measuredLatency) & " does NOT match expected latency of " & integer'image(Latency);
  end if;


  wait;
end process CheckLatency_proc;

  --
  -- Read In Stimulus
  --
  ReadFile_proc : process
    file     inputFile  : text;
    variable fileLine   : line;
    variable comma_char : character;
    variable A_real_in  : string(LengthA downto 1);
    variable A_imag_in  : string(LengthA downto 1);
    variable B_real_in  : string(LengthB downto 1);
    variable B_imag_in  : string(LengthB downto 1);

    variable A_real_vec   : signed(LengthA-1 downto 0);
    variable A_imag_vec   : signed(LengthA-1 downto 0);
    variable B_real_vec   : signed(LengthB-1 downto 0);
    variable B_imag_vec   : signed(LengthB-1 downto 0);

  begin

    -- read in file
    wait until rising_edge(Clock);
    file_open(inputFile, read_filename, read_mode);
    Reset <= '0';

    -- loop through file line-by-line
    while not endfile(inputFile) loop
      -- trigger read
      wait until rising_edge(Clock);

      -- read in multiplicand real and imag. components
      readline(inputFile, fileLine);
      read(fileLine, A_real_in);
      read(fileLine, comma_char);
      read(fileLine, A_imag_in);
      read(fileLine, comma_char);
      read(fileLine, B_real_in);
      read(fileLine, comma_char);
      read(fileLine, B_imag_in);

      -- copy over A real from file (string) into vector
      for i in LengthA downto 1 loop
        A_real_vec(i-1) := std_logic'value("'" & A_real_in(i) & "'");
      end loop;

      -- copy over A imag from file (string) into vector
      for i in LengthA downto 1 loop
        A_imag_vec(i-1) := std_logic'value("'" & A_imag_in(i) & "'");
      end loop;

      -- copy over B real from file (string) into vector to be fed into B_in
      for i in LengthB downto 1 loop
        B_real_vec(i-1) := std_logic'value("'" & B_real_in(i) & "'");
      end loop;

      -- copy over B imag from file (string) into vector to be fed into B_in
      for i in LengthB downto 1 loop
        B_imag_vec(i-1) := std_logic'value("'" & B_imag_in(i) & "'");
      end loop;

      -- feed test multiplicands into multiplier; theoretical C_out into signal to be read later
      RealA_in <= A_real_vec;
      ImagA_in <= A_imag_vec;
      RealB_in <= B_real_vec;
      ImagB_in <= B_imag_vec;

      -- input is valid for this clock
      SampleInValid <= '1';

    end loop;

    -- We're still on the clock where the last sample was driven into UUT.
    SampleInLast <= '1';
    wait for ClockPeriod;
    SampleInLast <= '0';

    -- input is no longer valid.
    SampleInValid <= '0';

    -- test behavior of SampleInReady / SampleOutReady control signals
    wait for ClockPeriod;
    SampleOutReady <= '1';
    wait for ClockPeriod;
    SampleOutReady <= '0';


    file_close(inputFile);

    wait;

  end process ReadFile_proc;

  --
  -- Write Out Results
  --
  LogFile_proc : process
    variable Result  : line;
  begin

  file_open(write_file, write_filename, write_mode);

  -- trigger
  loop
    wait until rising_edge(Clock);
    exit when SampleOutValid = '1';
  end loop;

  loop
    -- write real part of result in string format
    for x in ProductReal'length-1 downto 0 loop
      if ProductReal(x) = '1' then
        write(Result, integer'image(1));
      elsif ProductReal(x) = '0' then
        write(Result, integer'image(0));
      else
        write(Result, string'("X"));
      end if;
    end loop;

    write(Result, string'(","));

    -- write imaginary part of result in string format
    for x in ProductImaginary'length-1 downto 0 loop
      if ProductImaginary(x) = '1' then
        write(Result, integer'image(1));
      elsif ProductImaginary(x) = '0' then
        write(Result, integer'image(0));
      else
        write(Result, string'("X"));
      end if;

    end loop;

    -- write line to file
    writeline(write_file, Result);
    wait until rising_edge(clock);

    exit when SampleOutValid = '0';

  end loop;

  file_close(write_file);
  wait for 10*ClockPeriod;

  assert false report "test done" severity failure;

  end process;


end Behavioral;
